services:
  flask-app:
    build: .
    ports:
      - "80:5000" 
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase          
      MYSQL_USER: user                     
      MYSQL_PASSWORD: password             
    ports:
      - "3306:3306" 

  test:
    build: .
    command: python -m unittest

