name: Build & Test

on: [push, pull_request]

jobs:
  Docker-Build:
    runs-on: self-hosted

    steps:
    # for PR & Push
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running Unit Tests
        run: |
          docker compose run test 

    # for Push only 
      - name: Docker Setup
        uses: docker/setup-buildx-action@v3
        if: github.event_name == 'push'

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name == 'push'

      - name: Docker Build & push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: |
            dunaalsulaiman/capstone-project:latest
            dunaalsulaiman/capstone-project:${{ github.run_number }}
            dunaalsulaiman/capstone-project:${{ github.sha }}
          cache-from: dunaalsulaiman/capstone-project:latest
          cache-to: type-inline
        if: github.event_name == 'push'