name: Deployment

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: self-hosted 

    strategy:
      matrix:
        server: 
          - ${{ vars.SERVER_1_HOST }}
          - ${{ vars.SERVER_2_HOST }}

    steps:

      - name: deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

        run: |
          # ssh-keyscan ${{ matrix.server }} >> ~/.ssh/known_hosts
          # echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          # chmod 600 ~/.ssh/github_actions
          echo "running in ${{ matrix.server }}" 
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@${{ matrix.server }} << 'EOF' 
          docker pull dunaalsulaiman/capstone-project:latest
          docker rm -f web
          cd /capstone-project && docker run -d -p 80:5000 --name web  --env-file .env dunaalsulaiman/capstone-project:latest
          EOF

