name: Deployment

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: self-hosted 

    strategy:
      matrix:
        server: 
          - ${{ vars.SERVER_1_HOST }}
          - ${{ vars.SERVER_2_HOST }}

    steps:

      - name: deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

        run: |
          ssh-keyscan ${{ matrix.server }} >> ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          echo "running in ${{ matrix.server }}" 
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@${{ matrix.server }} << 'EOF' 
            docker stop $(docker ps -q --filter 'publish=80')
            docker pull dunaalsulaiman/capstone-project:latest
            sed -i 's/build: \./image: dunaalsulaiman\/capstone-project:latest/' /capstone-project/docker-compose.yaml
            docker compose up --build -d

          EOF
